### ğŸ“Š My Stats

[![RaÃºl's GitHub Streak](https://streak-stats.demolab.com/?user=raulgm00&theme=radical)](https://git.io/streak-stats)

<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://raw.githubusercontent.com/raulgm00/raulgm00/output/github-contribution-grid-snake-dark.svg">
  <source media="(prefers-color-scheme: light)" srcset="https://raw.githubusercontent.com/raulgm00/raulgm00/output/github-contribution-grid-snake.svg">
  <img alt="github contribution grid snake animation" src="https://raw.githubusercontent.com/raulgm00/raulgm00/output/github-contribution-grid-snake.svg">
</picture>

[<img src="https://img.shields.io/badge/LinkedIn-0077B5?style=for-the-badge&logo=linkedin&logoColor=white" />](https://www.linkedin.com/in/raul-ulises-garcia-moreno/)
